import {
  index,
  jsonb,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";
import { companies } from "./companies.js";

export const companyTokenLaunches = pgTable(
  "company_token_launches",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    companyId: uuid("company_id").notNull().references(() => companies.id),
    stage: text("stage"),
    companyWebsiteUrl: text("company_website_url"),
    businessSummary: text("business_summary"),
    tractionSummary: text("traction_summary"),
    launchRationale: text("launch_rationale"),
    socialLinks: jsonb("social_links").$type<Record<string, string | null>>().notNull().default({}),
    tokenName: text("token_name"),
    tokenSymbol: text("token_symbol"),
    tokenDescription: text("token_description"),
    imageUrl: text("image_url"),
    tweetUrl: text("tweet_url"),
    tokenWebsiteUrl: text("token_website_url"),
    selectedFeeWalletAddress: text("selected_fee_wallet_address"),
    latestSimulationFingerprint: text("latest_simulation_fingerprint"),
    latestSimulation: jsonb("latest_simulation").$type<Record<string, unknown>>(),
    latestSimulationAt: timestamp("latest_simulation_at", { withTimezone: true }),
    deployedTokenAddress: text("deployed_token_address"),
    deployedPoolId: text("deployed_pool_id"),
    deployedTxHash: text("deployed_tx_hash"),
    deployedActivityId: text("deployed_activity_id"),
    deployedChain: text("deployed_chain"),
    deployedFeeDistribution: jsonb("deployed_fee_distribution").$type<Record<string, unknown>>(),
    deployedAt: timestamp("deployed_at", { withTimezone: true }),
    deploymentUnknownAt: timestamp("deployment_unknown_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    companyUniqueIdx: uniqueIndex("company_token_launches_company_uq").on(table.companyId),
    companyDeployedIdx: index("company_token_launches_company_deployed_idx").on(
      table.companyId,
      table.deployedTokenAddress,
    ),
  }),
);
